apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-management-system
  labels:
    app: portfolio-app
    tier: backend
    env: local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-app
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: portfolio-app
        tier: backend
        env: local
    spec:
      containers:
        - name: portfolio-management-system-app
          image: limon408/portfolio_management_system:v5
          envFrom:
            - configMapRef:
                name: portfolio-config-map
            - secretRef:
                name: portfolio-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
