apiVersion: v1
kind: Service
metadata:
  name: portfolio-management-service
spec:
  type: NodePort
  selector:
    app: portfolio-app
    tier: backend
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30007
